"""update in student profile

Revision ID: 16d1c3d99332
Revises: 7ddb11d4354b
Create Date: 2026-06-20 22:36:23.800734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16d1c3d99332'
down_revision = '7ddb11d4354b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('cgpa',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('graduation_year',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('resume',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.alter_column('resume',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('graduation_year',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cgpa',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('branch',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
