"""add created_at to placement drive

Revision ID: 7ddb11d4354b
Revises: 
Create Date: 2026-06-20 18:13:29.343692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddb11d4354b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('placement_drives', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
